### ISSUE TITLE
Seg fault with lots of SNPs

### ISSUE THREAD

**Issue by eriqande** [eriqande/newhybrids#1]
Greg Owen emailed me with this:

Hi Dr. Anderson,

I'm trying to use your program NewHybrids on a large SNP dataset of hybrids and I'm having an error. I couldn't get the older version to work because I don't have a mac old enough, so I've been using the new version on github. 

I installed it and ran the test dataset, which worked. When I run it with my own data I have problems when there is a lot of data. I have about 8000 snps and 145 individuals which I'd like to use. When I try the full dataset it gives me a bunch of errors that look like:

WARNING: i=6 >= Num=6 in IntegerFromProbsRV().  Probably only a problem while initializing the chain.  i reset to 2
WARNING: i=6 >= Num=6 in IntegerFromProbsRV().  Probably only a problem while initializing the chain.  i reset to 0
...etc
Segmentation fault: 11

I tried trimming my dataset down and at about 375 loci it works some of the time, but above that it gives me the error every time I try to run it. Does the program just not work with many loci? 

I've attached two different input files, one with 400 loci that doesn't work and one with 350 loci that does. 

Also for reference I'm using mac OS X 10.9.3 with a 2.8 GHz Intel Core i7 and 8 GB of ram. 

Thanks for your help. 
### Solution:

It appears that the problem is caused by PofZ's for individuals that are NaN in the early sweeps of the run causing a bad access in the histogram increment function from MCTypes.  Should be able to fix this.

Made a fix in https://github.com/eriqande/eca-shared/commit/1d46b81081ad5cdaf9bb30f7304c297253633514

**Comment by cbossu** [comment]
Hello,
 Thanks for the fix, but I find that using 600 loci and ~250 individuals (mostly hybrids) still results in this warning and I have several NaN in PofZ that never fully resolve. I thought given enough time, a long burnin and a large number of generations, individual assignment would work, but this is not the case.  I've even reduced our genotypes to include only variants in previously defined 'outlier' regions.  Any insights would be great!!  Cheers,

Christen
