### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by hedgington** [eriqande/newhybrids#4]
Hi Eric,
I've run into an issue installing NewHybrids- after following the installation instructions here on github my test run stops with no results and I get the following warning in the errors log:

Warning!  Cannot open color scheme file NewHybrids_UDColorSchemes.txt...

Warning!  Cannot open file NewHybrids_UserDefdViews.txt in /Users/hilaryedgington/Library/gfmcmc.  Home is /Users/hilaryedgington...

I've tried to look for these files to move them into my library directory (as was suggested with the NewHybrids_PreDefdViews.txt file) and can't seem to find them anywhere- is there something I'm missing?

Thanks!
Hilary

**Comment by eriqande** [comment]
Hi Hilary,

I think what is happening there is that, when you are using the GUI version, you need to hit the space bar to start the program running.  Give that a whirl.  

I have updated the README to mention this, as it isn't transparent for people using the GUI.  Thanks for alerting me to that issue.

The Warnings are not a problem.  The program is just looking for files that you might have defined.  It is not an error and is not causing any problems.

I think this should take care of it all for you.  Let me know if you have any other issues.  Good luck with your data analysis.

Best wishes,

eric

**Comment by hedgington** [comment]
That was indeed my issue, it's working perfectly now.  Thanks for the quick response!
